# Generated by Django 4.2.1 on 2023-06-06 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MyUser",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=255, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("full_name", models.CharField(max_length=500)),
                ("is_admin", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user_mail",
                    models.EmailField(default="test@gmail.com", max_length=254),
                ),
                ("lead_full_name", models.CharField(max_length=230)),
                ("lead_full_name_possesive", models.CharField(max_length=250)),
                ("lead_interest", models.TextField()),
                ("lead_social_links", models.TextField()),
                ("lead_experience", models.TextField()),
                ("company_city", models.CharField(max_length=200)),
                ("company_state", models.CharField(max_length=202)),
                ("company_site", models.CharField(max_length=205)),
                ("company", models.CharField(max_length=500)),
                ("lead_skills", models.TextField()),
                ("lead_position", models.CharField(max_length=206)),
            ],
        ),
        migrations.CreateModel(
            name="Business_case_data",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(default="test@gmail.com", max_length=254)),
                ("Avg_BDR_Salary", models.FloatField()),
                ("Avg_BDR_Training_Costs", models.FloatField()),
                ("Avg_BDR_Benefits", models.FloatField()),
                ("Annual_Organization_BDR_Costs", models.FloatField()),
                ("Daily_Organization_BDR_Costs", models.FloatField()),
                ("Hourly_Organization_BDR_Costs", models.FloatField()),
                ("Monthly_Organization_BDR_Costs", models.FloatField(default=0)),
                ("Contacts_Monthly", models.FloatField(default=0)),
                ("Contacts_Daily", models.FloatField(default=0)),
                ("Contacts_Hourly", models.FloatField(default=0)),
                ("Leads_Monthly", models.FloatField(default=0)),
                ("Contact_to_Lead_Rate", models.FloatField(default=0)),
                ("contacts_to_generate_each_lead", models.FloatField(default=0)),
                ("leads_needed_to_generate_each_sale", models.FloatField(default=0)),
                ("ABDD_contacts_per_hour", models.FloatField()),
                ("ABDD_contacts_per_day", models.FloatField()),
                ("ABDD_contacts_per_month", models.FloatField()),
                ("ABDD_cost_per_year", models.FloatField()),
                ("ABDD_cost_per_month", models.FloatField()),
                ("ABDD_cost_per_day", models.FloatField()),
                ("ABDD_cost_per_hour", models.FloatField()),
                ("ABDD_cost_per_minute", models.FloatField()),
                ("ABDD_cost_per_second", models.FloatField()),
                ("savings_per_month", models.FloatField()),
                ("savings_per_year", models.FloatField()),
                ("saving_rate", models.FloatField()),
                ("unfruitful_contact_rate", models.FloatField()),
                ("organization_unfruitful_contacts_monthly", models.FloatField()),
                ("organization_unfruitful_contacts_daily", models.FloatField()),
                ("organization_unfruitful_contacts_hourly", models.FloatField()),
                ("organization_unfruitful_costs_monthly", models.FloatField()),
                ("organization_unfruitful_costs_daily", models.FloatField()),
                ("organization_unfruitful_costs_hourly", models.FloatField()),
                ("Organization_Lead_Generation_Rate_daily", models.FloatField()),
                ("Organization_Lead_Generation_Rate_hourly", models.FloatField()),
                ("ABDD_Lead_Generation_Rate_daily", models.FloatField(default=0)),
                ("ABDD_Lead_Generation_Rate", models.FloatField()),
                ("Organization_Avg_Cost_Per_Lead", models.FloatField()),
                ("ABDD_Avg_Cost_Per_Lead", models.FloatField()),
                ("CPL_Reduction", models.FloatField()),
                ("Organization_Sell_Generation_Rate", models.FloatField()),
                ("Avg_Organization_BDR_Cost_to_Generate_Sale", models.FloatField()),
                ("Avg_ABDD_Cost_to_Generate_Sale", models.FloatField()),
                ("seller_name", models.CharField(default="seller", max_length=200)),
                ("company", models.CharField(default="test", max_length=200)),
                ("Accounts_needed", models.FloatField(default=0)),
                ("Rev_share", models.FloatField(default=0)),
                ("org_abdd_process_ratio", models.FloatField(default=0)),
                ("ind_abdd_process_ratio", models.FloatField(default=0)),
                (
                    "background_email",
                    models.TextField(
                        default="still procesing email, check back again..."
                    ),
                ),
                (
                    "prospect_report",
                    models.TextField(
                        default="still procesing prospect report, check back again..."
                    ),
                ),
                (
                    "background_text",
                    models.TextField(
                        default="still procesing prospect text, check back again..."
                    ),
                ),
                (
                    "dashboard_link",
                    models.CharField(default="email@email.com", max_length=300),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.lead"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
