# Generated by Django 4.2.1 on 2023-05-29 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=500)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Business_case_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='test@gmail.com', max_length=254)),
                ('Avg_BDR_Salary', models.FloatField()),
                ('Avg_BDR_Training_Costs', models.CharField(max_length=250)),
                ('Avg_BDR_Benefits', models.CharField(max_length=100)),
                ('Annual_Organization_BDR_Costs', models.FloatField()),
                ('Daily_Organization_BDR_Costs', models.FloatField()),
                ('Hourly_Organization_BDR_Costs', models.FloatField()),
                ('Contacts_Monthly', models.FloatField()),
                ('Leads_Monthly', models.FloatField()),
                ('Contact_to_Lead_Rate', models.FloatField()),
                ('contacts_to_generate_each_lead', models.FloatField()),
                ('leads_needed_to_generate_each_sale', models.FloatField()),
                ('ABDD_contacts_per_hour', models.FloatField()),
                ('ABDD_contacts_per_day', models.FloatField()),
                ('ABDD_contacts_per_month', models.FloatField()),
                ('ABDD_cost_per_year', models.FloatField()),
                ('ABDD_cost_per_month', models.FloatField()),
                ('ABDD_cost_per_day', models.FloatField()),
                ('ABDD_cost_per_hour', models.FloatField()),
                ('ABDD_cost_per_minute', models.FloatField()),
                ('ABDD_cost_per_second', models.FloatField()),
                ('savings_per_month', models.FloatField()),
                ('savings_per_year', models.FloatField()),
                ('saving_rate', models.FloatField()),
                ('unfruitful_contact_rate', models.FloatField()),
                ('organization_unfruitful_contacts_monthly', models.FloatField()),
                ('organization_unfruitful_contacts_daily', models.FloatField()),
                ('organization_unfruitful_contacts_hourly', models.FloatField()),
                ('organization_unfruitful_costs_monthly', models.FloatField()),
                ('organization_unfruitful_costs_daily', models.FloatField()),
                ('organization_unfruitful_costs_hourly', models.FloatField()),
                ('Organization_Lead_Generation_Rate_daily', models.FloatField()),
                ('Organization_Lead_Generation_Rate_hourly', models.FloatField()),
                ('ABDD_Lead_Generation_Rate', models.FloatField()),
                ('Organization_Avg_Cost_Per_Lead', models.FloatField()),
                ('ABDD_Avg_Cost_Per_Lead', models.FloatField()),
                ('CPL_Reduction', models.FloatField()),
                ('Organization_Sell_Generation_Rate', models.FloatField()),
                ('Avg_Organization_BDR_Cost_to_Generate_Sale', models.FloatField()),
                ('Avg_ABDD_Cost_to_Generate_Sale', models.FloatField()),
                ('seller_name', models.CharField(default='seller', max_length=200)),
                ('company', models.CharField(default='test', max_length=200)),
                ('Accounts_needed', models.FloatField(default=0)),
                ('Rev_share', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
