# Generated by Django 4.2.1 on 2023-05-29 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_case_data',
            name='background_email',
            field=models.TextField(default='still procesing email, check back again...'),
        ),
    ]
