# Generated by Django 4.2.1 on 2023-05-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_book_business_case_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_case_data',
            name='company',
            field=models.CharField(default='test', max_length=200),
        ),
        migrations.AddField(
            model_name='business_case_data',
            name='seller_name',
            field=models.CharField(default='seller', max_length=200),
        ),
    ]
