# Generated by Django 4.2.1 on 2023-05-24 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_business_case_data_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_case_data',
            name='Accounts_needed',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='business_case_data',
            name='Rev_share',
            field=models.FloatField(default=0),
        ),
    ]
